%%
% T1 = New frame generated by transforming T by the screw defined by q,s,h
% and distance theta

% Make a skew sym func!!!!!!!!!!!!!!!!!!!

function (T1,S1) = screwTransf(T,q,s,h,theta)

omega = s; % Angular velocity of screw vector. Assuming theta_dot = 1 rad/s, 
% and therefore angular velocity is a unit vector in the direction of the
% screw axis
omega_hat = [0 -omega(3) omega(2); omega(3) 0 -omega(1); -omega(2) omega(1) 0],
v = [cross(-s,q) + h*s]'; % Linear velocity of screw vector

%S = [omega;v];
S_mat = [omega_hat v; zeros(1,4)];

% CHECK!!!!!!!!!
S_exp = expm(S_mat*theta); % Exponential coordinates for screw transformation

% Return T1
T1 = S_exp*T;

% Intermediate angles

% Plot


%% Calculate Screw Axis returning T1 to fix-frame origin
T_orig = [1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1];

% Calculate screw tranformation from T1 to origin
S1_exp = T_orig*inv(T1);

% Extract rotation matrix and origin vector from S1_exp, compute omega and theta
R1 = S1_exp(1:3,1:3);
p = S1_exp(1:3,4);

[omega1,theta1] = rotToAxisAngle(R1) % Check negative!

omega1_hat = [0 -omega1(3) omega1(2); omega1(3) 0 -omega1(1); -omega1(2) omega1(1) 0],

v1 = ((1/theta1)*eye(3) - (1/2)*omega1_hat + ((1/theta1)-.5*cot(theta1/2))*omega1_hat^2)*p;

S1_mat = [omega1_hat v1; zeros(1,4)]
S1 = [omega1;v1]

end

