%% ME384R - ASBR - THA1
% Written by Clara Summerford and Nathan Lovell
%
% This function takes a user-defined frame and set of screw axis parameters
% and computes the fixed-frame rigid body transformation of the frame along
% the screw axis. It also returns the screw axis associated with the
% transformation of the new frame back to the origin of the fixed frame.
%
% Inputs:
% T = Pose of a body frame defined with respect to the fixed frame
% q = a vector from the origin of T to a point on screw axis unit vector s
% s = screw axis unit vector 
% h = pitch of the screw
% theta = distance traveled along the screw
%
% Outputs:
% T1 = New frame generated by transforming T by the screw defined by q,s,h
% and distance theta (in the fixed frame)
% S1 = 6x1 Screw axis that describes the transformation of frame T1 back
% to the origin of the fixed frame


% Make a skew sym func!!!!!!!!!!!!!!!!!!!
% Plotting func?


function [T1,S1] = screwTransf(T,q,s,h,theta)

w = s; % Angular velocity of screw vector. Taking theta_dot = 1 rad/s, 
% the angular velocity is a unit vector in the direction of the
% screw axis.
w_hat = [0 -w(3) w(2); w(3) 0 -w(1); -w(2) w(1) 0],
v = [cross(-s,q) + h*s]'; % Linear velocity of screw vector

%S = [omega;v];
%S_mat = [omega_hat v; zeros(1,4)];

% Calculate the screw matrix exponential
%S_exp2 = expm(S_mat*theta) % Exponential coordinates for screw transformation
rod = eye(3) + sin(theta)*w_hat + (1-cos(theta))*w_hat^2; % Rodriguez' formula
star = (eye(3)*theta + (1-cos(theta))*w_hat + (theta-sin(theta))*w_hat^2)*v;
S_exp = [rod star; 0 0 0 1] % Exponential coordinates for screw transformation

% Return T1
T1 = S_exp*T;

% Compute the frame associated with a distance of 1/4, 1/2, and 3/4 of
% theta
theta_q = theta/4; % Quarter of theta
rod_q = eye(3) + sin(theta_q)*w_hat + (1-cos(theta_q))*w_hat^2; % Rodriguez' formula
star_q = (eye(3)*theta_q + (1-cos(theta_q))*w_hat + (theta_q-sin(theta_q))*w_hat^2)*v;
S_exp_q = [rod_q star_q; 0 0 0 1] % Exponential coordinates for screw transformation
T1_q = S_exp_q*T;

theta_h = theta/2; % Half of theta
rod_h = eye(3) + sin(theta_h)*w_hat + (1-cos(theta_h))*w_hat^2; % Rodriguez' formula
star_h = (eye(3)*theta_h + (1-cos(theta_h))*w_hat + (theta_h-sin(theta_h))*w_hat^2)*v;
S_exp_h = [rod_h star_h; 0 0 0 1] % Exponential coordinates for screw transformation
T1_h = S_exp_h*T;

theta_3q = 3*theta/4; % Three-quarters of theta
rod_3q = eye(3) + sin(theta_3q)*w_hat + (1-cos(theta_3q))*w_hat^2; % Rodriguez' formula
star_3q = (eye(3)*theta_3q + (1-cos(theta_3q))*w_hat + (theta_3q-sin(theta_3q))*w_hat^2)*v;
S_exp_3q = [rod_3q star_3q; 0 0 0 1] % Exponential coordinates for screw transformation
T1_3q = S_exp_3q*T;

%%% Plot
zf(1) = figure(1);
za(1) = axes;

%%% Space Frame
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_s = [0 0 0 1];
x_s = [1 0 0 1];
y_s = [0 1 0 1];
z_s = [0 0 1 1];
% Plot
zp(1) = quiver3(O_s(1),O_s(2),O_s(3),x_s(1),x_s(2),x_s(3),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
hold on
grid on
box on
zp(2) = quiver3(O_s(1),O_s(2),O_s(3),y_s(1),y_s(2),y_s(3),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(3) = quiver3(O_s(1),O_s(2),O_s(3),z_s(1),z_s(2),z_s(3),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');

za(1).XLim = [-8,8];
za(1).YLim = [-8,8];
za(1).ZLim = [-8,8];
za(1).XLabel.String = 'X';
za(1).YLabel.String = 'Y';
za(1).ZLabel.String = 'Z';

%%% T
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_T = T(1:4,4); % Origin of T1 in space frame
x_T = T*x_s'; % Location of x_hat arrowhead defined in body frame (must adjust below to get space frame)
y_T = T*y_s'; % Location of y_hat arrowhead defined in body frame (must adjust below to get space frame)
z_T = T*z_s'; % Location of z_hat arrowhead defined in body frame (must adjust below to get space frame)
zp(4) = quiver3(O_T(1),O_T(2),O_T(3),(x_T(1)-O_T(1)),(x_T(2)-O_T(2)),(x_T(3)-O_T(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
zp(5) = quiver3(O_T(1),O_T(2),O_T(3),(y_T(1)-O_T(1)),(y_T(2)-O_T(2)),(y_T(3)-O_T(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(6) = quiver3(O_T(1),O_T(2),O_T(3),(z_T(1)-O_T(1)),(z_T(2)-O_T(2)),(z_T(3)-O_T(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');

%%% T1
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_T1 = T1(1:4,4); % Origin of T1 in space frame
% Adjust homogenous representation of arrow heads to be points, not vectors
x_T(4) = 1;
y_T(4) = 1;
z_T(4) = 1;

x_T1 = S_exp*x_T;
y_T1 = S_exp*y_T;
z_T1 = S_exp*z_T;
% Plot
zp(7) = quiver3(O_T1(1),O_T1(2),O_T1(3),(x_T1(1)-O_T1(1)),(x_T1(2)-O_T1(2)),(x_T1(3)-O_T1(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
zp(8) = quiver3(O_T1(1),O_T1(2),O_T1(3),(y_T1(1)-O_T1(1)),(y_T1(2)-O_T1(2)),(y_T1(3)-O_T1(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(9) = quiver3(O_T1(1),O_T1(2),O_T1(3),(z_T1(1)-O_T1(1)),(z_T1(2)-O_T1(2)),(z_T1(3)-O_T1(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');

%%% T1_q
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_T1_q = T1_q(1:4,4); % Origin of T1 in space frame
% Adjust homogenous representation of arrow heads to be points, not vectors
x_T(4) = 1;
y_T(4) = 1;
z_T(4) = 1;

x_T1_q = S_exp_q*x_T;
y_T1_q = S_exp_q*y_T;
z_T1_q = S_exp_q*z_T;
% Plot
zp(10) = quiver3(O_T1_q(1),O_T1_q(2),O_T1_q(3),(x_T1_q(1)-O_T1_q(1)),(x_T1_q(2)-O_T1_q(2)),(x_T1_q(3)-O_T1_q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
zp(11) = quiver3(O_T1_q(1),O_T1_q(2),O_T1_q(3),(y_T1_q(1)-O_T1_q(1)),(y_T1_q(2)-O_T1_q(2)),(y_T1_q(3)-O_T1_q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(12) = quiver3(O_T1_q(1),O_T1_q(2),O_T1_q(3),(z_T1_q(1)-O_T1_q(1)),(z_T1_q(2)-O_T1_q(2)),(z_T1_q(3)-O_T1_q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');

%%% T1_h
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_T1_h = T1_h(1:4,4); % Origin of T1 in space frame
% Adjust homogenous representation of arrow heads to be points, not vectors
x_T(4) = 1;
y_T(4) = 1;
z_T(4) = 1;

x_T1_h = S_exp_h*x_T;
y_T1_h = S_exp_h*y_T;
z_T1_h = S_exp_h*z_T;
% Plot
zp(13) = quiver3(O_T1_h(1),O_T1_h(2),O_T1_h(3),(x_T1_h(1)-O_T1_h(1)),(x_T1_h(2)-O_T1_h(2)),(x_T1_h(3)-O_T1_h(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
zp(14) = quiver3(O_T1_h(1),O_T1_h(2),O_T1_h(3),(y_T1_h(1)-O_T1_h(1)),(y_T1_h(2)-O_T1_h(2)),(y_T1_h(3)-O_T1_h(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(15) = quiver3(O_T1_h(1),O_T1_h(2),O_T1_h(3),(z_T1_h(1)-O_T1_h(1)),(z_T1_h(2)-O_T1_h(2)),(z_T1_h(3)-O_T1_h(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');

%%% T1_3q
% Location of arrow tails (origin) and arrow heads - homogenous representation
O_T1_3q = T1_3q(1:4,4); % Origin of T1 in space frame
% Adjust homogenous representation of arrow heads to be points, not vectors
x_T(4) = 1;
y_T(4) = 1;
z_T(4) = 1;

x_T1_3q = S_exp_3q*x_T;
y_T1_3q = S_exp_3q*y_T;
z_T1_3q = S_exp_3q*z_T;
% Plot
zp(16) = quiver3(O_T1_3q(1),O_T1_3q(2),O_T1_3q(3),(x_T1_3q(1)-O_T1_3q(1)),(x_T1_3q(2)-O_T1_3q(2)),(x_T1_3q(3)-O_T1_3q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','r');
zp(17) = quiver3(O_T1_3q(1),O_T1_3q(2),O_T1_3q(3),(y_T1_3q(1)-O_T1_3q(1)),(y_T1_3q(2)-O_T1_3q(2)),(y_T1_3q(3)-O_T1_3q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','g');
zp(18) = quiver3(O_T1_3q(1),O_T1_3q(2),O_T1_3q(3),(z_T1_3q(1)-O_T1_3q(1)),(z_T1_3q(2)-O_T1_3q(2)),(z_T1_3q(3)-O_T1_3q(3)),'LineWidth',1.5,'MaxHeadSize',2,'Color','b');



%%% Calculate Screw Axis returning T1 to fix-frame origin
T_orig = eye(4);

% Calculate screw tranformation from T1 to origin
S1_exp = T_orig*inv(T1);

% Extract rotation matrix and origin vector from S1_exp, compute omega and theta
R1 = S1_exp(1:3,1:3);
p = S1_exp(1:3,4);
[w1,theta1] = rotToAxisAngle(R1) % Check negative!
w1_hat = [0 -w1(3) w1(2); w1(3) 0 -w1(1); -w1(2) w1(1) 0]; % Use Clara's function

% Calculate linear velocity vector (
v1 = ((1/theta1)*eye(3) - (1/2)*w1_hat + ((1/theta1)-.5*cot(theta1/2))*w1_hat^2)*p;

S1_mat = [w1_hat v1; zeros(1,4)]
S1 = [w1;v1]

end

