%% ME384R - ASBR - THA1
% Written by Clara Summerford and Nathan Lovell
%
% This function takes a user-defined frame and set of screw axis parameters
% and computes the fixed-frame rigid body transformation of the frame along
% the screw axis. It also returns the screw axis associated with the
% transformation of the new frame back to the origin of the fixed frame.
%
% Inputs:
% T = Pose of a body frame defined with respect to the fixed frame
% q = a vector from the origin of T to a point on screw axis unit vector s
% s = screw axis unit vector 
% h = pitch of the screw
% theta = distance traveled along the screw
%
% Outputs:
% T1 = New frame generated by transforming T by the screw defined by q,s,h
% and distance theta (in the fixed frame)
% S1 = 6x1 Screw axis that describes the transformation of frame T1 back
% to the origin of the fixed frame
%
% NOTE: User must manually adjust X,Y, and Z limits to the desired ranges
% for the plots. User will also need to uncomment the "print" lines in
% order to export the plots to png files.

function [T1,S1] = screwTransf(T,q,s,h,theta)

w = s; % Angular velocity of screw vector. Taking theta_dot = 1 rad/s, 
% the angular velocity is a unit vector in the direction of the
% screw axis.
w_hat = vec2SkewSym(w),
v = [cross(-s,q) + h*s]'; % Linear velocity of screw vector

% Calculate Screw Axis S
S = [w';v];
S_mat = [w_hat v; zeros(1,4)]; % Matrix representation of S1

% Calculate the screw matrix exponential
S_exp = calcScrewMatExp(w,v,theta);

% Return T1
T1 = S_exp*T;

% Compute the frames associated with a distance of 1/4, 1/2, and 3/4 of
% theta
theta_q = theta/4; % Quarter of theta
S_exp_q = calcScrewMatExp(w,v,theta_q);
T1_q = S_exp_q*T;

theta_h = theta/2; % Half of theta
S_exp_h = calcScrewMatExp(w,v,theta_h);
T1_h = S_exp_h*T;

theta_3q = 3*theta/4; % Three-quarters of theta
S_exp_3q = calcScrewMatExp(w,v,theta_3q);
T1_3q = S_exp_3q*T;

%%% Plot frames
plotTransf(eye(4))
hold on
xlim([-6,8])
ylim([-4,8])
zlim([-6,8])
xlabel('X')
ylabel('Y')
zlabel('Z')
plotTransf(T)
plotTransf(T,S_exp)
plotTransf(T,S_exp_q)
plotTransf(T,S_exp_h)
plotTransf(T,S_exp_3q)

zf(1) = figure(1);

% Export plot as a png
fig_size = [5 4];
zf(1).PaperPosition = [0 0 fig_size];
zf(1).PaperSize = fig_size;
ss = ['THA1 PA3 Plot 1']; % File Name
%print(zf(1),'-dpng','-r300','-vector',ss) % Uncomment to save figure


%%% Calculate Screw Axis returning T1 to fix-frame origin
T_orig = eye(4);

% Calculate screw tranformation from T1 to origin
S1_exp = T_orig*inv(T1);

% Extract rotation matrix and origin vector from S1_exp, compute omega and theta
R1 = S1_exp(1:3,1:3);
p = S1_exp(1:3,4);
[w1,theta1] = rotToAxisAngle(R1) % Check negative!
w1_hat = vec2SkewSym(w1);

% Calculate linear velocity vector
v1 = ((1/theta1)*eye(3) - (1/2)*w1_hat + ((1/theta1)-.5*cot(theta1/2))*w1_hat^2)*p;

% Calculate Screw Axis S1
S1 = [w1;v1]
% S1_mat = [w1_hat v1; zeros(1,4)] % Matrix representation of S1


%%% Plot 
t_range = 0:0.01:theta1;
S1_path = zeros(length(t_range),3);

for n = 1:length(t_range)
    S1_exp_int = calcScrewMatExp(w1,v1,t_range(n))
    T_int = S1_exp_int*T1; % Intermediate pose 
    S1_path(n,:) = T_int(1:3,4); % Path of the screw axis S1
end

% Plot Screw axis
path = plot3(S1_path(:,1),S1_path(:,2),S1_path(:,3), 'LineWidth',1,'Color','m','DisplayName','Screw Axis S1')
legend([path],{'Screw Axis S1'},'Location','northeast')

zf(2) = figure(1)

% Export plot as a png
fig_size = [5 4];
zf(2).PaperPosition = [0 0 fig_size];
zf(2).PaperSize = fig_size;
ss = ['THA1 PA3 Plot 2']; % File Name
%print(zf(2),'-dpng','-r300','-vector',ss) % Uncomment to save figure

end